---
language: ruby
timeouts:
  bundle: 600
rvm:
 - 1.9.3
 - 2.0.0
 - 2.2.0
env:
  global:
   - REDMINE_DIR=./workspace/redmine
   - PLUGIN_NAME=redmine_exception_handler
  matrix:
   - REDMINE=3.0-stable
   - REDMINE=v3.8.0
   - REDMINE=master
matrix:
  exclude:
   - rvm: 2.0.0
     env: REDMINE=v3.8.0
     gemfile: workspace/redmine/Gemfile
   - rvm: 2.2.0
     env: REDMINE=v3.8.0
     gemfile: workspace/redmine/Gemfile
  allow_failures:
   - env: REDMINE=v3.8.0
gemfile: workspace/redmine/Gemfile
before_install:
 - ./script/ci.sh clone_redmine --target $REDMINE_DIR
 - cp ./config/database.yml.travis $REDMINE_DIR/config/database.yml
 - ./script/ci.sh install_plugin_gemfile
install: ./script/ci.sh bundle_install
before_script:
 - mysql -e 'CREATE DATABASE redmine CHARACTER SET utf8;'
 - ./script/ci.sh prepare_redmine
 - ./script/ci.sh prepare_plugin
 - 'phantomjs --webdriver 4444 2>&- 1>&- &'
script:
 - ./script/ci.sh run_tests
 - ./script/ci.sh test_uninstall
